[__config__]
oldver = "current.json"
newver = "new.json"

[nvchecker]
source = "github"
github = "lilydjwg/nvchecker"
use_max_tag = true

[mcfly]
source = "github"
github = "cantino/mcfly"
use_max_tag = true
